#cloud-config

coreos:
  etcd2:
    listen-client-urls: http://${PRIVATE_IP}:2379,http://127.0.0.1:2379
    listen-peer-urls: http://${PRIVATE_IP}:2380
    initial-cluster: master=http://${MASTER_HOST}:2380
    proxy: on
  fleet:
    public-ip: ${PRIVATE_IP}
    metadata: role=worker${WORKER_NUMBER}
  flannel:
    etcd_endpoints: http://127.0.0.1:2379
    interface: ${PRIVATE_IP}

  units:
   - name: 00-eth0.network
      runtime: true
      content: |
        [Match]
        Name=eth0

        [Network]
        DNS=${PUBLIC_DNS_IP}
        Address=${PUBLIC_IP}/${PUBLIC_NETMASK}
        Gateway=${PUBLIC_GATEWAY_IP}

    - name: 00-eth1.network
      runtime: true
      content: |
        [Match]
        Name=eth1

        [Network]
        Address=${PRIVATE_IP}/${PRIVATE_NETMASK}

    - name: settimezone.service
      command: start
      content: |
        [Unit]
        Description=Set the time zone

        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone America/Recife
        RemainAfterExit=yes
        Type=oneshot

    - name: etcd2.service
      command: start

    - name: fleet.service
      command: start

    - name: flanneld.service
      command: start
      drop-ins:
        - name: 10-env-config.conf
          content: |
            [Service]
            EnvironmentFile=/run/flannel/options.env

    - name: docker.service
      command: start
      drop-ins:
        - name: 40-flannel.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Requires=flanneld.service
        After=flanneld.service

        [Service]
        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
        ExecStartPre=-/usr/bin/mkdir -p /etc/kubernetes
        ExecStartPre=/usr/bin/curl -L -o /etc/kubernetes/worker-kubeconfig.yaml https://raw.githubusercontent.com/carlosesdias/kubernetes/master/worker-kubeconfig.yaml
        ExecStartPre=/usr/bin/curl -L -o /opt/bin/kubelet -z /opt/bin/kubelet https://raw.githubusercontent.com/carlosesdias/kubernetes/master/bin/kubelet
        ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
        ExecStart=/opt/bin/kubelet \
        --api-servers=https://${MASTER_HOST} \
        --register-node=true \
        --allow-privileged=true \
        --hostname-override=${PRIVATE_IP} \
        --cluster-dns=${DNS_SERVICE_IP} \
        --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
        --tls-cert-file=/etc/kubernetes/ssl/worker.pem \
        --tls-private-key-file=/etc/kubernetes/ssl/worker-key.pem
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target

    - name: kube-proxy.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Proxy
        Requires=flanneld.service
        After=flanneld.service

        [Service]
        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
        ExecStartPre=-/usr/bin/mkdir -p /etc/kubernetes
        ExecStartPre=/usr/bin/curl -L -o /etc/kubernetes/worker-kubeconfig.yaml https://raw.githubusercontent.com/carlosesdias/kubernetes/master/worker-kubeconfig.yaml
        ExecStartPre=/usr/bin/curl -L -o /opt/bin/kube-proxy -z /opt/bin/kube-proxy https://raw.githubusercontent.com/carlosesdias/kubernetes/master/bin/kube-proxy
        ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-proxy
        ExecStart=/opt/bin/kube-proxy \
        --master=https://${MASTER_HOST} \
        --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
        --proxy-mode=iptables
        Restart=always
        RestartSec=10

